  - name: copying catalogue service into system service
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: daemon-reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name : starting and enabling service
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: yes